### ISSUE TITLE
Imperceptible buttons.

### ISSUE THREAD

**Issue by Lofty-Brambles** [WalkingPal/walking-pal-web#34] opened 2022-10-01 20:38 UTC
In the registrations page, the buttons available to be clicked on, as Previous and Next are really imperceptible and have no visual indicators as to when they are active and when they are not, as well as if they are even buttons. The tab navigation is messed up as well, the buttons dont get focused, but the cards do. I'd like to improve this.
![image](https://user-images.githubusercontent.com/100270817/193427409-8a6ac5e4-9bfd-440d-a074-1fd1385ba255.png)
![image](https://user-images.githubusercontent.com/100270817/193427417-1ee27861-0bae-49ab-984b-dd023bfad08b.png)

**Comment by ashuvssut** [comment] 2022-10-01 20:49
Hi! @Lofty-Brambles 

The 4 little indicators you are talking about, actually those are not buttons. those are simple indicators only. I think they animate  just fine. also, they are not meant to navigate through the form. they are just there to show the progress.

If I am missing something else you wanna tell, please correct me, else you may close this issue

**Comment by ashuvssut** [comment] 2022-10-01 20:51
I am a little concerned about the 2nd screenshot.  whats that large space on the right of the `NEXT` button? I think thats some UI glitch, how can we reproduce that ?

**Comment by astro3012** [comment] 2022-10-01 21:14
@ashuvssut I think the register screen could use a redesign. You don't need a multi step gamification UX here, as you are only taking in 4 pieces of related information.

The register page can follow same design language as other pages (Similar to FAQ, About), and instead of 4 steps, have a single vertical form takes in all the values. This way the user does not have to do additional clicks of going back to previous fields if they feel they have made an error. This would also maintain consistency throughout the app.

As for the bug, it's caused by pressing tab in any of the input fields.

**Comment by ashuvssut** [comment] 2022-10-01 21:27
oh, actually we do not plan to redesign the register screen.

you can work on that bug. its related to accessiblilty maybe. I am clueless about that

**Closed** 2022-10-01 21:28 UTC
